### ISSUE TITLE
スプレッドシート整理

### ISSUE THREAD

**Issue by okuokuch** [okuokuch/pokemon_sv_vs_support#115]
- [x] スプレッドシートを補完するフォルダを毎ドライブに作成
  - [x] 配布用
  - [x] 開発用
- [x] 趣味るさんに共有

**Comment by Syumiru** [comment]
@okuokuch 
ぼちぼちスプレッドシート改修しようとしているのですが、改めて開発用スプレッドシートのURL共有いただけますでしょうか？

**Comment by okuokuch** [comment]
@Syumiru 
すみません！作成しました。
配布用
https://drive.google.com/drive/folders/1w8sT_G3f_s37U0s--ItbwJjqAO1-oT-_?usp=sharing
開発用
https://drive.google.com/drive/folders/1AyW4cJHoFGGXRg9Hwbx1p86bcyKSlzE5?usp=sharing
です。開発用のスプレッドシートを編集できること確認出来たらクローズ予定です。

**Comment by Syumiru** [comment]
ご対応ありがとうございます！
編集者権限付与されていることを確認したのでクローズします。
