### ISSUE TITLE
【バグ】line botでパーティ登録時の登録行が不適切

### ISSUE THREAD

**Issue by okuokuch** [okuokuch/pokemon_sv_vs_support#117]
**バグの説明**
logページに、1行もデータが記述されていない状態で、LINE Bot経由でデータ登録しようとすると1000行目(一番下の行)にデータが追加される。

**再現方法**
その動作を再現するための手順を記述してください。
1. logページのデータを削除。
2. スプレッドシートに転送する用のLINE Bot経由でメッセージを送る。

**期待される動作**
logデータに一行もデータがない場合は、2行目にデータが記述されるようにする。

**補足事項**
GASの問題。
現在、1行1列のセルを選択し、Ctrl + 下を押下した場合に選択されるセルをもとに入力位置を決めている。
1行もデータがない場合は、Ctrl + 下により一番下のセルが選択され、そこに入力されてしまっている。

**Comment by okuokuch** [comment]
最終行の取得方法をgetLastRow()を利用する方法に変更予定。
https://for-dummies.net/gas-noobs/how-to-get-last-row-index-from-sheets-by-gas/#index_id1
他候補としてgetMaxRows()、getNextDataCell()、getRowIndex()を続けて使用する方法もある。
getLastRowでは、すべての列で最終行の行数を取得
getMaxRow~getRowIndexを利用する方では、特定列(A列など)の最終行の行数を取得
という違いがある。

**Comment by Syumiru** [comment]
ご対応ありがとうございました。以下の手順で検証し期待される動作を確認しましたので、クローズします。
①スクリプト更新
　修正行のみをgetLastRow()を使用した形に修正しデプロイ
②Webhook URL更新
　ウェブアプリURLをLINE DevelopersのWebhook URLを更新
③テスト実施

@okuokuch
ちなみに以下の手順を行った結果、今回のテスト結果どころかLINEから応答なしでした。（Webhook URLの検証は成功）
①スクリプト更新
　第二版開発用に紐づくスクリプトの5行目以下を、テスト対象のスプレッドシートに紐づくスクリプトへコピペしデプロイ
②Webhook URL更新
　ウェブアプリURLをLINE DevelopersのWebhook URLを更新
③テスト実施
