### ISSUE TITLE
シート「マイチーム分析」作成

### ISSUE THREAD

**Issue by okuokuch** [okuokuch/pokemon_sv_vs_support#121]

**Comment by okuokuch** [comment]
複数パーティを混ぜて選出率や初手率を計算しても有益な情報ではないと判断。(同じポケモンでもパーティによって役割が異なる場合、選出が大きく変わるから。)
なので1つのパーティに対して分析をするようなシートにしたい。
そうした場合、シングルだと選出方法は60通りになる(6P1 * 5C2)。なのでその全通りに対して、選出数、初手数、勝敗等を集計する。
参考)対戦補助エクセルの時に使用していた表。(レイアウトはこれにはしない。60通り集計するのイメージ用の図)


![Image](https://user-images.githubusercontent.com/94620772/229288188-0d0c1c02-a088-4fc6-ac42-a4aa2ce221fb.png)

**Comment by okuokuch** [comment]
@Syumiru 
マイチーム分析ページを作成しました。
チームIDを変更すると、データが更新されます。

備忘録
勝敗が不明だったり、選出ポケモンが空欄のものも集計してしまう状態です。この部分は今後修正できそうであれば行う。
無理そうであれば、マニュアルに注意書きをする。

**Comment by Syumiru** [comment]
以下機能を追加
- トータル勝利数の表示
- トータル勝率の表示
- 選出パターンごとの選出率の追加
- 選出パターンごとの勝率の追加

**Comment by okuokuch** [comment]
第二版でマイチーム分析シート作成済みなのでクローズします。
