### ISSUE TITLE
【機能要望】ロギング機能の追加提案

### ISSUE THREAD

**Issue by Syumiru** [okuokuch/pokemon_sv_vs_support#138]
【要件】
- 選出中や対戦中の記載内容（わざやもちもの、テラスタイプなど）をログとして残す
　例：選出中画面の選出内容をシート「log」へ反映させる

**Comment by Syumiru** [comment]
議事メモ
ログ読込ボタンを左上にした方が良い
→操作ミスを誘発するため。

**Comment by okuokuch** [comment]
実装済みのためクローズします。
