### ISSUE TITLE
ポケモンHOMEデータ取得

### ISSUE THREAD

**Issue by Syumiru** [okuokuch/pokemon_sv_vs_support#15]
- [ ] ポケモンランキング
- [x] 技
- [x] せいかく
- [x] 特性
- [x] テラスタイプ
- [x] アイテム

**Comment by okuokuch** [comment]
技ランキングを取得するコードの一部をGASに書き換え。
Pythonで記述していたコードの書き換えで実装できることを確認。(要リファクタリング)

**Comment by okuokuch** [comment]
@Syumiru 
スプレッドシートを開いたタイミングで、HOMEのデータを取得する機能を付けました。
また、相手情報のページを参照して取得したデータを表示するページを作りました。
ポケモン名の表記統一、レイアウトなどが必要で、MTG時に相談させてください。

**Comment by Syumiru** [comment]
> @Syumiru スプレッドシートを開いたタイミングで、HOMEのデータを取得する機能を付けました。 また、相手情報のページを参照して取得したデータを表示するページを作りました。 ポケモン名の表記統一、レイアウト検討などが必要で、MTG時に相談させてください。
ご対応ありがとうございます！承知しました。

**Comment by Syumiru** [comment]
【議事メモ】
ポケモンランキング（使用率ランク）の表示は未実装。理由は、選出中に不要な情報であるため。

**Comment by okuokuch** [comment]
SPARKLINEを設定。
性格の名称の後にステータス変化を追加。例)ようき(S↑C↓)
