### ISSUE TITLE
行動ログ作成補助ツール

### ISSUE THREAD

**Issue by okuokuch** [okuokuch/pokemon_sv_vs_support#192]
pythonファイルを修正し、対戦画面で表示された文字列をスクショする機能を追加する。
11/3時点でおおよそ完成しているが、エラーが発生し機能停止する場合があるのでその修正が必要。

**Comment by Syumiru** [comment]
【議事メモ】
対戦IDごとにフォルダ分けして出力した方が良いのでは？
→現状の仕様だと1つのフォルダ内に出力して対戦ID_通し番号とすることで1つの対戦に限らずスクロールで確認できるメリットがある
