### ISSUE TITLE
【機能要望】藍の円盤対応

### ISSUE THREAD

**Issue by Syumiru** [okuokuch/pokemon_sv_vs_support#193]
対応リスト

- アプリ関連
  - [x] テンプレート画像追加
- スプレッドシート関連
  - [x] pokemon_status追加
  - [x] HOME用データ追加(HOME_アイテム名etc.)
  - [x] 虹テラス関連の仕様変更
- 番外編対応
  - [x] pokemon_status追加
  - [x] HOME用データ追加

**あなたの機能要求は問題に関連していますか？**
何が問題なのか、明確かつ簡潔な説明を記述してください。
例 私はいつも[...]のときにイライラしています。

**あなたが望む解決策**
あなたが解決したいことの明確かつ簡潔な説明を記述してください。

**検討した代替案**
あなたが検討した代替案や機能についての明確かつ簡潔な説明を記述してください。

**補足事項**
機能要望に関するその他のコンテキストやスクリーンショットをここに追加してください。

**Comment by Syumiru** [comment]
テスラって虹テラスのことですかね？（ストーリー未クリア）

**Comment by okuokuch** [comment]
ステラ(通称：虹テラス)の誤字ですね。修正しました。
