### ISSUE TITLE
logから対戦分析用の各種数値取得検討

### ISSUE THREAD

**Issue by okuokuch** [okuokuch/pokemon_sv_vs_support#51]
## 背景
スプレッドシート関数のみで対戦分析シートの計算を実装すると処理時間が長くなる。
GASを用いて、処理量を減らすことで処理時間短縮を目指す
#42 の派生

## サブタスク一覧

- [x] ポケモン名をユニークに取得するロジック作成
- [x] チーム数 | 選出数 | 先発数 | を取得するロジック作成(ポケモン名をカウント)
- [x] 勝利数を取得するロジック作成(勝敗でフィルタして、ポケモン数をカウント)
- [x] team_idでデータ取得する範囲を可変にするロジック作成
- [x] triggerでGASを実行するロジック作成
- [x] 自分チーム分析用の関数作成
- [ ] APIを叩く回数最小化
- [x] TN/順位を取得

## 参考
https://tonari-it.com/gas-spreadsheet-find/
処理を早くするためにはAPIを叩く回数を少なくすることが重要らしい。

**Comment by Syumiru** [comment]
https://github.com/okuokuch/pokemon_sv_vs_support/issues/179#issuecomment-1722474372

**Comment by Syumiru** [comment]
関連コメント転記
https://github.com/okuokuch/pokemon_sv_vs_support/issues/185#issuecomment-1762933544

**Comment by okuokuch** [comment]
残タスクを#174 に転記したのでクローズ
