### ISSUE TITLE
とくせい耐性を含めたタイプ相性

### ISSUE THREAD

**Issue by Syumiru** [okuokuch/pokemon_sv_vs_support#9]
【仕様】
以下①～④のを選択して表示可能にする。（現状、①のみ実装）
①使用率が1番高い特性を考慮し耐性表示（デフォルト設定）
②耐性を無視して表示
③使用率が2番高い特性を考慮し耐性表示
④使用率が3番高い特性を考慮し耐性表示

耐性付与アイテムや、天候、フィールドによる耐性変更は今回実装しない。

**Comment by Syumiru** [comment]
【仕様】
耐性とくせいをもっているポケモンについて、耐性も考慮してタイプ相性を表示する。
【例外】
ふゆう、たいねつの耐性特性を複数もったポケモン（ドータクン）は、どちらも考慮してタイプ相性が表示される。
例：ふゆうによりじめん無効、たいねつによりほのお半減の最強ドータクン

**Comment by Syumiru** [comment]
耐性付与アイテムについてもどうするか相談したいです。
例：ふうせんサーフゴー

**Comment by okuokuch** [comment]
特性体制は実装する。
体制付与アイテムや、天候、フィールドは実装しない。→ポケモン特有の個性ではないから。

**Comment by okuokuch** [comment]
特性耐性の実装流れ
1. 全特性耐性を反映させる
2. 全特性耐性or特性選択を選べるようにする
3. 特性選択し単一特性の補正を反映させる

**Comment by okuokuch** [comment]
承知しました！よろしくお願いします。
仕様の議論に加え、保守性維持のために中間テーブルをどのように作るべきかについても実物見ながら話できればと思います。

**Comment by Syumiru** [comment]
以下の仕様を追加予定です。
以下①～④のを選択して表示可能にする。（現状、①のみ実装）
①使用率が1番高い特性を考慮し耐性表示（デフォルト設定）
②耐性を無視して表示
③使用率が2番高い特性を考慮し耐性表示
④使用率が3番高い特性を考慮し耐性表示

**Comment by Syumiru** [comment]
実装済のためクローズします。
