### ISSUE TITLE
プロジェクトとリポジトリのpublic/privateの関係について

### ISSUE THREAD

**Issue by Syumiru** [okuokuch/pokemon_sv_vs_support#93]
@okuokuch 
リポジトリをpublicにするにあたり、
privateのプロジェクトとプロジェクトに紐づくissueがどういった扱いになるのか疑問があります。

特に問題あるわけではないので、どのように表示されるのかは公開してからのお楽しみでもよい気がしてますが、気づいたので起票しておきます。

**Comment by okuokuch** [comment]
@Syumiru 
このリポジトリをパブリックにしました。
githubにログインしていない状態でissueを確認して以下がわかりました。
### わかったこと
- issueはすべて閲覧可能
- issueに紐づけてあるprivateのprojectは閲覧不可
  - 関連projectがなしとして表示されていました。

ということで、内々のコミュニケーションをとりたい場合はこのリポジトリとは関係ない場所で行うということですね！

**Comment by Syumiru** [comment]
なるほど！検証ありがとうございます！
承知しました！

**Comment by Syumiru** [comment]
検証済のためクローズします。
